### ISSUE TITLE
mulitple cookies fail

### ISSUE THREAD

**Issue by dobe** [storborg/livetest#1]
when setting multiple cookies, only the first in the mapping gets sent because of a bug in BaseCookie handling. **str** of BaseCookie returns Set-Cookie header lines, so this should not be used to create client side Cookie headers

in **init**.py around line 84 , the cookie handling should look like this

```
    if self.cookies:
        c = BaseCookie()
        for name, value in self.cookies.items():
            c[name] = value
        hc = '; '.join(['='.join([m.key, m.value]) for m in c.values()])
        req.headers['Cookie'] = hc
```

this bug is also in webtest currently, and it looks like its exatly the problem here http://trac.pythonpaste.org/pythonpaste/ticket/238

cheers bernd

**Comment by storborg** [comment]
fix bug where only the first cookie gets sent. closed by 9e6c05a4f5e460d13558d99de3e97e1c31af2d2e.
