### ISSUE TITLE
Failure if WebTest >= 1.2.2

### ISSUE THREAD

**Issue by quodt** [storborg/livetest#2]
Since WebTest 1.2.2 reverted it's changes to use SimpleCookie instead of BaseCookie again the import of livetest will fail.
To avoid failures the dependency to WebTest should get nailed to version >1.2 and <1.2.2 or the usage of BaseCookie should be changed.

**Comment by scompt** [comment]
Fixed in 7cb26ea6ead70c60f3e937bdf5b55dac70340666
